services:
  markdown-toc:
    build: "./markdown-toc"
    ports:
      - "8080:80"

  markdown-toc-frontend:
    build: "./markdown-toc-frontend"
    ports:
      - "8081:80"
    depends_on:
      - markdown-toc
