apiVersion: v1
kind: Service
metadata:
  name: markdown-toc-frontend
  labels:
    app: markdown-toc-app
spec:
  type: LoadBalancer
  ports:
  - port: 80 # service's incoming port
    targetPort: 80 # pods' incoming port
    nodePort: 30001 # should be removed in production
  selector:
    app: markdown-toc-app
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: markdown-toc-frontend
  labels:
    app: markdown-toc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: markdown-toc-app
      tier: frontend
  template:
    metadata:
      labels:
        app: markdown-toc-app
        tier: frontend
    spec:
      containers:
      - name: markdown-toc-frontend
        image: ventus218/markdown-toc-frontend
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
          limits:
            cpu: 100m
